#!/usr/bin/env bash
set -e

function fail {
    echo "FAIL: $1" 1>&2
    exit 1
}

DIR=~/Programming/Haskell/AstPlugin
cd "$DIR"
[[ -d "dist" ]] && rm -r dist
nix-build --show-trace -E 'import ./test.nix'
