#!/usr/bin/env bash
shopt -s nullglob

function mktest {
    echo "Making test for '$1'"
    NAME="custom-pkg.$1"
    pushd scripts > /dev/null    &&
    ln -s custom-pkgs "$NAME"    &&
    popd > /dev/null             &&
    touch "results/stderr/$NAME" &&
    touch "results/stdout/$NAME"
}

function packageNames {
    BASE=~/.nixpkgs/custom
    # "Local" is where we keep "regular" packages
    for FILE in "$BASE"/local/*.nix
    do
        basename "$FILE" .nix
    done

    # "Imports" are usually special-cases
    for FILE in "$BASE"/imports/*.nix
    do
        basename "$FILE" .nix
    done

    # Haskell packages need prefixing by the compiler version
    for FILE in "$BASE"/haskell/*.nix
    do
        NAME=$(basename "$FILE" .nix)
        for PREFIX in haskellPackages
        do
            echo "$PREFIX.$NAME"
        done
    done

    # One offs (usually overrides)
    echo get_iplayer
}

function mkExpr {
    # Since Nix is lazy, knowing that an expression exists doesn't tell us much;
    # we must try to build it, in order to expose problems.
    # We face two difficulties: not everything is a package, and those which are
    # need to be forced.

    # Packages are just attribute sets, so inspecting the type doesn't help us.
    # As a heuristic, if something contains a "src", it's probably a package
    echo "if ($1) ? src then ($1)"

    # If a package has no "src", it might be generated programatically by a
    # "buildCommand"
    echo "else if ($1) ? buildCommand then ($1)"

    # If we've not been given a package, fall back to a safe default like bash
    echo "else bash"
}

# Get the package to test from our invocation name
PKG=$(basename "$0" | cut -c 12-)

ERR=0
if [[ -z "$PKG" ]]
then
    # No package given, make sure we have all of them

    # All custom Nix expressions should have a test
    while read -r PKG
    do
        echo "Checking we have a test for '$PKG'"
        [[ -e "scripts/custom-pkg.$PKG" ]] || {
            echo "'$PKG' doesn't have a test" >> /dev/stderr
            mktest "$PKG" || ERR=1
        }
    done < <(packageNames)

    # All tests must correspond to a Nix expression
    for SCRIPT in scripts/custom-pkg.*
    do
        echo "Checking there is a Nix expression for '$SCRIPT'"
        PKG=$(basename "$SCRIPT" | cut -c 12-)
        FOUND=$(nix-instantiate  \
                    --show-trace \
                    --eval       \
                    --expr "let pkgs = import <nixpkgs> {}; in pkgs ? $PKG")
        [[ "x$FOUND" = "xtrue" ]] || {
            echo "'$PKG' doesn't seem to be a package" >> /dev/stderr
            ERR=1
        }
    done
    exit "$ERR"
else
    # Got a package, try to build it
    EXPR=$(mkExpr "$PKG")
    nix-shell --show-trace --run true -p "$EXPR" || {
        echo "Couldn't invoke nix-shell for '$PKG'" >> /dev/stderr
        exit 1
    }
fi
