#!/usr/bin/env bash
echo "Checking for panhandle binary"
nix-shell --show-trace -p panhandle -p which --run 'which panhandle' || {
    echo "panhandle binary not installed" >> /dev/stderr
    exit 1
}

MARKDOWN="*foo*"
echo "Got Markdown '$MARKDOWN'"

JSON=$(echo "$MARKDOWN" | nix-shell -p pandoc --run "pandoc -f markdown -t json")
echo "Got JSON '$JSON'"

TICK='`'
TICKS="${TICK}${TICK}${TICK}"
UNWRAP=$(echo "$TICKS"; echo '{.unwrap}'; echo "$JSON"; echo "$TICKS")
echo "Got unwrap '$UNWRAP'"

HTML=$(echo "$UNWRAP" | nix-shell -p pandoc -p panhandle --run \
                            "pandoc --filter panhandle -f markdown -t html") || {
    echo "Failed to check JSON" >> /dev/stderr
    exit 1
}
echo "Got HTML '$HTML'"

echo "$HTML" | grep '<em>foo</em>' || {
    echo "Didn't unwrap *foo* in '$HTML'" >> /dev/stderr
    exit 1
}
